[package]
name = "moonfire-base"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
readme = "../README.md"
edition = "2018"
license-file = "../../LICENSE.txt"

[features]
nightly = []

[lib]
path = "lib.rs"

[dependencies]
failure = "0.1"
futures = "0.3"
lazy_static = "1"
libc = "0.2"
log = "0.4"
parking_lot = "0.12"
nom = "7.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slab = "0.4"
time = "0.1"
